### ISSUE TITLE
[suggestion] Benchmarck Ionic

### ISSUE THREAD

**Issue by LifeIsStrange** [BramDC3/Cocktailr#11]
Pleaase :)
Especially since it has react support, it shouldn't be too much work porting code from the react native version of cocktailr. 

(this issue is in reference to your blog post:
https://blog.codemagic.io/flutter-vs-ios-android-reactnative-xamarin/)

Most people have this old belief that chromium is slower than native but this shouldn't be true anymore and I believe that chromium has the fastest 2D renderer there is. 
After all they use skia and ANGLE (same as flutter and Android native) but those libs are made by and for chromium as the first class citizen.

Actually if you get data showing that Ionic is the fastest, your blog would get a lot of views as it would be one of the first blogs to show the inflexion point of native vs web performance.

**Comment by BramDC3** [comment]
Hey LifeIsStrange

I'm currently spending all my time into Flutter, I'm not very passionate about Ionic. I hope it can inspire you to conduct your own experiment :)
